Grid:
    NX: 256  # number of X gridcells
    NY: 256  # number of Y gridcells

Sim:
    FastForward: 1 # plot just every nth time step
    Timesteps: 500  # number of timesteps per epoch
    RhoPred: 0.2  # density of predators
    RhoPrey: 0.215  # density of preys

Prey:
    Pflee: 0.4  # probability to flee
    Pbreed: 0.2  # prob to mate
    FoodReserve: 4  # initial food reserve
    FoodReserveMax: 8  # maximum food reserve

Pred:
    Pbreed: 0.2  # prob to mate
    FoodReserve: 4  # see above
    FoodReserveMax: 8  # see above


Plots:
    filepath: "plots/"
    figsize: !!python/tuple [5, 5]  # important to tell python that this is a tuple
    format: 'pdf'
    DPI: 150
