Grid:
    NX: 100  # number of X gridcells
    NY: 100  # number of Y gridcells
    ResRate: 0.5  # rate of resource regrowing

Sim:
    NEpoch: 20  # number of epochs the simulation should run
    NPred: 100  # number of predators
    NPrey: 100  # number of preys

Prey:
    Pflee: 0.25  # probability to flee
    Pmate: 0.4  # prob to mate
    #Rules: "NN"  # using neural network rules
    Rules: "default"  #using default prey rules
    Score: -1  # this should be more precise, but not possible atm

Pred:
    Pmate: 0.5  # prob to mate
    #Rules: "NN"  # using neural network rules
    Rules: "default"  # using default predator rules
    Score: -1  # this should be more precise, but not possible atm
