# configuration file for the actor-critic PPM
Model:
    dim:                !!python/tuple [128, 128]  # dimensionality
    densities:          !!python/tuple [0.2, 0.215]  # Predator, Prey
    food_reserve:       3
    max_food_reserve:   8
    generation:         0
    p_breed:            0.2
    p_flee:             0.4
    p_eat:              0.6  # = 1-p_flee
    rewards:            {} # kept empty for the moment

Sim:
    steps:              1000
    episodes:           100

Plot:
    filepath:           "plots/"
    figsize:            !!python/tuple [9,12]
    format:             "png"
    DPI:                300
